server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: service-registry
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#  instance:
#    hostname: localhost